version: '3'
services:
    web:
        container_name: nginx-web-server
        image: nginx:latest
        ports:
            - "83:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    laravel:
        container_name: laravel-app       
        build:
            context: .
            dockerfile: PHP.Dockerfile
        image: laravel-app
        volumes:
            - ./app:/app
    database:
        container_name: database-mariadb
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'pluralsight_mariadb'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3307:3306
        command: --max-allowed-packet=104857600
volumes:
    mysqldata: {}